AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  NewRelicLicenseKey:
    Type: String
    Description: The New Relic account license key
    Default: 'YOUR_LICENSE_KEY'

Resources:
  NewRelicLogIngestion:
    Type: AWS::Serverless::Application    
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:5558675309:applications/NewRelic-log-ingestion
        SemanticVersion: 2.0.0
      Parameters:
        NRLicenseKey: !Ref NewRelicLicenseKey
